name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install glut
      run: sudo apt-get install freeglut3-dev
    - name: Install Qt
      run: sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
    - name: Run QMake
      run: qmake
    - name: make
      run: make
